import 'package:json_annotation/json_annotation.dart'
    show JsonKey, JsonSerializable;

part 'customer_attributes.g.dart';

/// Represents additional customer attributes to be sent during registration.
///
/// This class defines various optional customer attributes that can be included
/// with the customer registration request. These attributes can be used to
/// personalize the customer's experience within the Gameball platform.
@JsonSerializable()
class CustomerAttributes {
  /// The customer's display name (optional).
  @JsonKey(name: "displayName")
  String? displayName;

  /// The customer's first name (optional).
  @JsonKey(name: "firstName")
  String? firstName;

  /// The customer's last name (optional).
  @JsonKey(name: "lastName")
  String? lastName;

  /// The customer's email address (optional).
  @JsonKey(name: "email")
  String? email;

  /// The customer's gender (optional).
  @JsonKey(name: "gender")
  String? gender;

  /// The customer's mobile number (optional).
  @JsonKey(name: "mobile")
  String? mobileNumber;

  /// The customer's date of birth in a format suitable for the API (optional).
  @JsonKey(name: "dateOfBirth")
  String? dateOfBirth;

  /// The customer's join date in a format suitable for the API (optional).
  @JsonKey(name: "joinDate")
  String? joinDate;

  /// The customer's preferred language (optional).
  @JsonKey(name: "preferredLanguage")
  String? preferredLanguage;

  /// The channel through which the customer joined (defaults to "mobile").
  @JsonKey(name: "channel", defaultValue: "mobile")
  String? channel;

  /// A map containing additional custom customer attributes (optional).
  @JsonKey(name: "custom")
  Map<String, String>? customAttributes;

  /// Creates a new `CustomerAttributes` object.
  ///
  /// Arguments (all optional):
  ///   - `displayName`: The customer's display name.
  ///   - `firstName`: The customer's first name.
  ///   - `lastName`: The customer's last name.
  ///   - `email`: The customer's email address.
  ///   - `gender`: The customer's gender.
  ///   - `mobileNumber`: The customer's mobile number.
  ///   - `dateOfBirth`: The customer's date of birth (API format).
  ///   - `joinDate`: The customer's join date (API format).
  ///   - `preferredLanguage`: The customer's preferred language.
  ///   - `channel`: The channel through which the customer joined (defaults to "mobile").
  ///   - `customAttributes`: A map of additional custom customer attributes.
  CustomerAttributes({
    this.displayName,
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.mobileNumber,
    this.dateOfBirth,
    this.joinDate,
    this.preferredLanguage,
    this.channel,
    this.customAttributes,
  });

  /// Converts the `CustomerAttributes` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package.
  Map<String, dynamic> toJson() => _$CustomerAttributesToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory CustomerAttributes.fromJson(Map<String, dynamic> json) =>
      _$CustomerAttributesFromJson(json);
}
