import 'package:json_annotation/json_annotation.dart';

part 'event.g.dart';

/// Represents an event to be sent to the Gameball API.
///
/// This class defines the structure of an event object with properties
/// for event data, customer Id, optional mobile number, and optional email.
@JsonSerializable()
class Event {
  /// A map containing the actual event data.
  /// The key represents the event type, and the value is a map containing additional event-specific data.
  @JsonKey(name: "events")
  Map<String, Map<String, Object>> events;

  /// The unique identifier of the customer associated with the event.
  @JsonKey(name: "customerId")
  String customerId;

  /// The customer's mobile number (optional).
  @JsonKey(name: "mobile")
  String? mobileNumber;

  /// The customer's email address (optional).
  @JsonKey(name: "email")
  String? email;

  /// Creates a new `Event` object.
  ///
  /// Arguments:
  ///   - `events`: The event data map (required).
  ///   - `customerId`: The customer's unique identifier (required).
  ///   - `mobileNumber`: The customer's mobile number (optional).
  ///   - `email`: The customer's email address (optional).
  Event({
    required this.events,
    required this.customerId,
    this.mobileNumber,
    this.email,
  });

  /// Converts the `Event` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package.
  Map<String, dynamic> toJson() => _$EventToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
}
