import 'package:json_annotation/json_annotation.dart'
    show JsonKey, JsonSerializable;

import '../../utils/platform_utils.dart';
import 'customer_attributes.dart';

part 'initialize_customer_request.g.dart';

/// Represents the data structure for a customer registration request to the Gameball API.
///
/// This class defines the properties required to register a customer with the Gameball platform.
/// It includes essential information for identifying the customer, as well as optional details
/// to enrich their profile and personalize their experience.
@JsonSerializable()
class InitializeCustomerRequest {
  /// The unique identifier for the customer (required).
  ///
  /// This identifier should uniquely identify the customer within your application and persist
  /// across device changes or app re-installs. You are responsible for generating
  /// and managing this unique Id.
  @JsonKey(name: "customerId")
  String customerId;

  /// The customer's device token for push notifications (required).
  ///
  /// This token is used by Gameball to send push notifications to the customer's device.
  /// You'll need to implement a mechanism to obtain the device token from your
  /// platform-specific notification framework (e.g., Firebase Cloud Messaging or Apple Push Notification service).
  @JsonKey(name: "deviceToken")
  String deviceToken;

  /// The operating system type of the customer's device (optional, automatically set).
  ///
  /// This value is automatically determined based on the current platform (iOS, Android, or other)
  /// and is included in the registration request for informational purposes.
  @JsonKey(name: "osType")
  String? osType;

  /// Additional customer attributes to be sent during registration (optional).
  ///
  /// This can include details such as the customer's display name, email address, mobile number,
  /// date of birth, and custom attributes specific to your application. These attributes can
  /// be used by Gameball to personalize the customer's experience within the platform.
  @JsonKey(name: "customerAttributes")
  CustomerAttributes? customerAttributes;

  /// A referral code associated with the customer (optional).
  ///
  /// If a referral code is provided, it can be used to track referrals and potentially offer
  /// rewards to both the referring and referred customers.
  @JsonKey(name: "referrerCode")
  String? referrerCode;

  /// The customer's email address (optional).
  ///
  /// You can include the customer's email address if you plan to use email-based communication
  /// or for other purposes within your application.
  @JsonKey(name: "email")
  String? email;

  /// The customer's mobile number (optional).
  ///
  /// You can include the customer's mobile number if you plan to use SMS-based communication
  /// or for other purposes within your application.
  @JsonKey(name: "mobile")
  String? mobileNumber;

  /// A flag indicating if the individual interacting with your system is a guest (not signed up).
  ///
  /// Set to `true` for guest users. If `false` or omitted, the individual is treated
  /// as a registered customer by default.
  @JsonKey(name: "guest")
  bool? isGuest;

  @JsonKey(name: "pushServiceProvider")
  String? pushProvider;

  /// Creates a new `InitializeCustomerRequest` object.
  ///
  /// Arguments:
  ///   - `customerId` (required): The unique identifier for the customer.
  ///   - `deviceToken` (required): The customer's device token.
  ///   - `osType` (optional): The operating system type. Automatically set based on the platform if not provided.
  ///   - `customerAttributes` (optional): Additional attributes related to the customer.
  ///   - `referrerCode` (optional): A referral code associated with the customer.
  ///   - `email` (optional): The customer's email address.
  ///   - `mobileNumber` (optional): The customer's mobile number for communication purposes.
  ///   - `isGuest` (optional): A flag indicating if the customer is a guest or not.
  InitializeCustomerRequest({
    required this.customerId,
    required this.deviceToken,
    this.osType,
    this.customerAttributes,
    this.referrerCode,
    this.email,
    this.mobileNumber,
    this.isGuest,
    this.pushProvider
  }) {
    osType = getDevicePlatform(); // Automatically set osType based on platform
  }

  /// Converts the `InitializeCustomerRequest` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package
  /// to serialize the object before sending it to the Gameball API.
  Map<String, dynamic> toJson() => _$InitializeCustomerRequestToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory InitializeCustomerRequest.fromJson(Map<String, dynamic> json) =>
      _$InitializeCustomerRequestFromJson(json);
}
