import 'package:json_annotation/json_annotation.dart'
    show JsonKey, JsonSerializable;

part 'player_attributes.g.dart';

/// Represents additional player attributes to be sent during registration.
///
/// This class defines various optional player attributes that can be included
/// with the player registration request. These attributes can be used to
/// personalize the player's experience within the Gameball platform.
@JsonSerializable()
class PlayerAttributes {
  /// The player's display name (optional).
  @JsonKey(name: "displayName")
  String? displayName;

  /// The player's first name (optional).
  @JsonKey(name: "firstName")
  String? firstName;

  /// The player's last name (optional).
  @JsonKey(name: "lastName")
  String? lastName;

  /// The player's email address (optional).
  @JsonKey(name: "email")
  String? email;

  /// The player's gender (optional).
  @JsonKey(name: "gender")
  String? gender;

  /// The player's mobile number (optional).
  @JsonKey(name: "mobile")
  String? mobileNumber;

  /// The player's date of birth in a format suitable for the API (optional).
  @JsonKey(name: "dateOfBirth")
  String? dateOfBirth;

  /// The player's join date in a format suitable for the API (optional).
  @JsonKey(name: "joinDate")
  String? joinDate;

  /// The player's preferred language (optional).
  @JsonKey(name: "preferredLanguage")
  String? preferredLanguage;

  /// The channel through which the player joined (defaults to "mobile").
  @JsonKey(name: "channel", defaultValue: "mobile")
  String? channel;

  /// A map containing additional custom player attributes (optional).
  @JsonKey(name: "custom")
  Map<String, String>? customAttributes;

  /// Creates a new `PlayerAttributes` object.
  ///
  /// Arguments (all optional):
  ///   - `displayName`: The player's display name.
  ///   - `firstName`: The player's first name.
  ///   - `lastName`: The player's last name.
  ///   - `email`: The player's email address.
  ///   - `gender`: The player's gender.
  ///   - `mobileNumber`: The player's mobile number.
  ///   - `dateOfBirth`: The player's date of birth (API format).
  ///   - `joinDate`: The player's join date (API format).
  ///   - `preferredLanguage`: The player's preferred language.
  ///   - `channel`: The channel through which the player joined (defaults to "mobile").
  ///   - `customAttributes`: A map of additional custom player attributes.
  PlayerAttributes({
    this.displayName,
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.mobileNumber,
    this.dateOfBirth,
    this.joinDate,
    this.preferredLanguage,
    this.channel,
    this.customAttributes,
  });

  /// Converts the `PlayerAttributes` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package.
  Map<String, dynamic> toJson() => _$PlayerAttributesToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory PlayerAttributes.fromJson(Map<String, dynamic> json) =>
      _$PlayerAttributesFromJson(json);
}
