import 'package:json_annotation/json_annotation.dart';

part 'initialize_customer_response.g.dart';

/// Represents the response from a successful customer registration request.
///
/// This class encapsulates the `gameballId` assigned to the newly registered customer
/// by the Gameball API.
@JsonSerializable()
class InitializeCustomerResponse {
  /// The unique identifier assigned to the customer by Gameball.
  int gameballId;

  /// Creates a new `InitializeCustomerResponse` object.
  ///
  /// Arguments:
  ///   - `gameballId`: The Gameball ID assigned to the customer.
  InitializeCustomerResponse(this.gameballId);

  /// Converts the `InitializeCustomerResponse` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package.
  Map<String, dynamic> toJson() => _$InitializeCustomerResponseToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory InitializeCustomerResponse.fromJson(Map<String, dynamic> json) =>
      _$InitializeCustomerResponseFromJson(json);
}
