import 'package:json_annotation/json_annotation.dart';

part 'player_register_response.g.dart';

/// Represents the response from a successful player registration request.
///
/// This class encapsulates the `gameballId` assigned to the newly registered player
/// by the Gameball API.
@JsonSerializable()
class PlayerRegisterResponse {
  /// The unique identifier assigned to the player by Gameball.
  int gameballId;

  /// Creates a new `PlayerRegisterResponse` object.
  ///
  /// Arguments:
  ///   - `gameballId`: The Gameball ID assigned to the player.
  PlayerRegisterResponse(this.gameballId);

  /// Converts the `PlayerRegisterResponse` object to a JSON map.
  ///
  /// This method is typically used internally by the `json_serializable` package.
  Map<String, dynamic> toJson() => _$PlayerRegisterResponseToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory PlayerRegisterResponse.fromJson(Map<String, dynamic> json) =>
      _$PlayerRegisterResponseFromJson(json);
}
